# Generated by Django 4.0.3 on 2024-03-18 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placesforu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImageModel',
        ),
    ]
